#!/usr/bin/env bash
#
# TRUE blue-green zero-downtime deploy for homenshop-next.
#
#   ACTIVE colour keeps serving the whole time. We build + boot the INACTIVE
#   colour into its own dist dir + port, health-check it, then flip the nginx
#   upstream and reload nginx (atomic). The old colour is deleted only after
#   the flip, so its dist dir survives as an instant rollback target.
#
#   blue  → PORT 3000, .next-blue
#   green → PORT 3001, .next-green
#
# Usage:  bash scripts/deploy-blue-green.sh
# Rollback: bash scripts/rollback-blue-green.sh
#
set -euo pipefail

APP_DIR="/var/www/homenshop-next"
UPSTREAM_CONF="/etc/nginx/conf.d/00-nextjs-upstream.conf"
STATE_FILE="$APP_DIR/.active-color"
HEALTH_TIMEOUT=60   # seconds to wait for the new colour to answer 200/307/308
GRACE=9             # seconds to let in-flight requests drain before killing old

cd "$APP_DIR"

port_for() { [ "$1" = "blue" ] && echo 3000 || echo 3001; }

ACTIVE="$(cat "$STATE_FILE" 2>/dev/null || echo blue)"
[ "$ACTIVE" = "green" ] && TARGET="blue" || TARGET="green"
ACTIVE_PORT="$(port_for "$ACTIVE")"
TARGET_PORT="$(port_for "$TARGET")"
TARGET_DIR=".next-$TARGET"

echo "==> Active colour: $ACTIVE (:$ACTIVE_PORT)   →   deploying to: $TARGET (:$TARGET_PORT)"

# 1. Pull + deps
echo "==> git pull"
git pull --rebase --autostash

echo "==> npm install"
npm install --prefer-offline --no-audit --no-fund

# 2. Prisma client — ALWAYS regenerate (idempotent; gating it caused stale-client build failures)
echo "==> prisma generate"
npx prisma generate

# 3. Defensive: wipe type/dev artifacts for BOTH colours (+ legacy .next).
#    next build auto-appends .next-blue/types AND .next-green/types to
#    tsconfig "include"; if the two colours were built from different code
#    their route unions conflict during typecheck (e.g. a route in one but
#    not the other). These dirs are compile-time only — runtime reads
#    server/ + static/ — so deleting the live colour's types/ is safe. The
#    target's types/ is regenerated by this build, leaving only one union.
rm -rf .next/types .next/dev \
       .next-blue/types .next-blue/dev \
       .next-green/types .next-green/dev

# 4. Build into the INACTIVE colour's dist dir. Live colour untouched.
echo "==> build → $TARGET_DIR"
NEXT_DIST_DIR="$TARGET_DIR" npm run build

# 5. Sanity check the build is complete (reject half-empty builds)
if [ ! -d "$TARGET_DIR/server" ] || [ ! -d "$TARGET_DIR/static" ]; then
  echo "!! build incomplete ($TARGET_DIR/server or /static missing) — aborting, live colour untouched"
  exit 1
fi

# 6. Boot the target colour fresh (ensures correct NEXT_DIST_DIR/PORT env)
echo "==> boot hns-$TARGET"
pm2 delete "hns-$TARGET" >/dev/null 2>&1 || true
pm2 start ecosystem.config.cjs --only "hns-$TARGET" --update-env

# 7. Health-check the new colour on its OWN port (not through nginx yet)
echo "==> health-check :$TARGET_PORT (up to ${HEALTH_TIMEOUT}s)"
ok=0
for i in $(seq 1 "$HEALTH_TIMEOUT"); do
  code="$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:$TARGET_PORT/" || true)"
  case "$code" in
    200|307|308) ok=1; echo "   healthy after ${i}s (HTTP $code)"; break ;;
  esac
  sleep 1
done
if [ "$ok" != "1" ]; then
  echo "!! hns-$TARGET never went healthy — rolling back boot, keeping $ACTIVE live"
  pm2 delete "hns-$TARGET" >/dev/null 2>&1 || true
  exit 1
fi

# 8. Flip the nginx upstream → atomic traffic switch on reload
echo "==> flip nginx upstream → :$TARGET_PORT"
cat > "$UPSTREAM_CONF" <<EOF
# Managed by deploy-blue-green.sh — DO NOT edit by hand.
# Active colour: $TARGET (:$TARGET_PORT)  @ $(date -u +%FT%TZ)
upstream nextjs {
    server 127.0.0.1:$TARGET_PORT;
    keepalive 32;
}
EOF
if ! nginx -t; then
  echo "!! nginx -t failed after upstream flip — reverting upstream file, keeping $ACTIVE live"
  cat > "$UPSTREAM_CONF" <<EOF
upstream nextjs {
    server 127.0.0.1:$ACTIVE_PORT;
    keepalive 32;
}
EOF
  pm2 delete "hns-$TARGET" >/dev/null 2>&1 || true
  exit 1
fi
nginx -s reload

# 9. Record new active colour
echo "$TARGET" > "$STATE_FILE"
echo "==> active colour is now: $TARGET"

# 10. Drain + retire the old colour (its dist dir stays for rollback)
echo "==> draining old colour (${GRACE}s) then deleting hns-$ACTIVE"
sleep "$GRACE"
pm2 delete "hns-$ACTIVE" >/dev/null 2>&1 || true
pm2 save

echo "==> DONE. Live: $TARGET (:$TARGET_PORT). Rollback target preserved: $ACTIVE (.next-$ACTIVE)."
